Update yml for unique timestamped directory fix

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -100,21 +100,25 @@ jobs:
               run: |
                   TIMESTAMP=$(date +'%Y-%m-%d_%H-%M-%S')
                   mkdir -p published-reports/$TIMESTAMP
-                  cp -r playwright-report/* published-reports/$TIMESTAMP
-                  echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_ENV
-            - name: Update Index Page
-              run: |
-                  INDEX_FILE="published-reports/index.html"
-                  TIMESTAMP_REGEX="^[0-9]{4}-[0-9]{2}-[0-9]{2}_[0-9]{2}-[0-9]{2}-[0-9]{2}$"
-                  echo "<html><body><h1>Playwright Reports</h1><table border='1'><tr><th>Run Timestamp</th><th>Report Link</th></tr>" > $INDEX_FILE
-                  for dir in $(ls -d published-reports/*/); do
-                  TIMESTAMP=$(basename $dir)
-                  if [[ $TIMESTAMP =~ $TIMESTAMP_REGEX ]]; then
-                    LINK="<a href='./$TIMESTAMP/index.html'>$TIMESTAMP</a>"
-                    echo "<tr><td>$TIMESTAMP</td><td>$LINK</td></tr>" >> $INDEX_FILE
+                  if [ -d "playwright-report" ] && [ "$(ls -A playwright-report)" ]; then
+                    cp -r playwright-report/* published-reports/$TIMESTAMP
+                    echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_ENV
+                  else
+                    echo "Error playwright-report directory is empty or missing!" && exit 1
                   fi
-                  done
-                  echo "</table></body></html>" >> $INDEX_FILE
+                  - name: Update Index Page
+                  run: |
+                      INDEX_FILE="published-reports/index.html"
+                      TIMESTAMP_REGEX="^[0-9]{4}-[0-9]{2}-[0-9]{2}_[0-9]{2}-[0-9]{2}-[0-9]{2}$"
+                      echo "<html><body><h1>Playwright Reports</h1><table border='1'><tr><th>Run Timestamp</th><th>Report Link</th></tr>" > $INDEX_FILE
+                      for dir in $(find published-reports/ -maxdepth 1 -mindepth 1 -type d | sort); do
+                          TIMESTAMP=$(basename $dir)
+                          if [[ $TIMESTAMP =~ $TIMESTAMP_REGEX ]]; then
+                              LINK="<a href='./$TIMESTAMP/index.html'>$TIMESTAMP</a>"
+                              echo "<tr><td>$TIMESTAMP</td><td>$LINK</td></tr>" >> $INDEX_FILE
+                          fi
+                      done
+                      echo "</table></body></html>" >> $INDEX_FILE
             - name: Highlight Current Run
               run: |
                   cp -r published-reports/$TIMESTAMP published-reports/latest
@@ -128,8 +132,6 @@ jobs:
               with:
                   name: upload-html-reports
                   path: published-reports/
-            - name: Wait for Artifact to be available
-              run: sleep 30 # Wait for 30 seconds to allow artifact processing
             - name: Setup Pages
               uses: actions/configure-pages@v2
             - name: Upload artifact
